KS-2-4 bonus ores
Rey5l/kotlin_sprint pull request #10
Opened 2024-09-20 08:22 UTC by Rey5l

2024-09-20 13:45 UTC, ievetrovdev requested changes

2024-09-20 13:45 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +const val FIFTY_PERCENT = 0.2
Для возможности гибкой работы с кодом, следует инициализировать согласно ТЗ проценты целым числом 20. И уже потом производить вычисление процентов. Таким образом, если нужен будет другой процент, достаточно будет поменять значение в одном месте.
И именно поэтому это число не константа, бафф потенциально может меняться

2024-09-20 14:42 UTC, Rey5l commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +const val HUNDRED_PERCENT = 100
А вот так вот если сделать, будет ошибкой?

2024-09-21 06:46 UTC, ievetrovdev approved these changes

2024-09-21 06:46 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +const val HUNDRED_PERCENT = 100
нет, тут 100 не будет изменяться. Хоть в таких базовых числах для которых контекст не нужен, константа не обязательна.

2024-09-21 09:12 UTC, merged