KS-1-3 takeoff and landing times
Rey5l/kotlin_sprint pull request #4
Opened 2024-09-16 14:49 UTC by Rey5l

2024-09-17 07:14 UTC, ievetrovdev requested changes

2024-09-17 07:14 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task3.kt
> +    println(year)
В целом результат есть! но в примере в ТЗ цифры начинаются с 0.
Вообще нормальная практика, если сервер присылает дату или время строкой.
Давай объявим строки и сделаем правильный формат)

2024-09-17 10:50 UTC, Rey5l commented on src/main/kotlin/lesson1/lesson1_task3.kt
> +    println(year)
Ааа, наконец-то дошло)

2024-09-19 07:49 UTC, ievetrovdev approved these changes
Да, отлично

2024-09-19 21:43 UTC, merged